name: get_thumbnail_video
description: A flutter plugin for creating a thumbnail from a local video file or from a video URL.
version: 0.6.1
repository: https://github.com/Alberto-Monteiro/video_thumbnail

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=2.0.0"

dependencies:
  flutter:
    sdk: flutter
  cross_file: ^0.3.3+4
  flutter_web_plugins:
    sdk: flutter
  plugin_platform_interface: ^2.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.2
  lints: ^2.1.1

flutter:
  plugin:
    implements: video_thumbnail
    platforms:
      android:
        package: xyz.justsoft.video_thumbnail
        pluginClass: VideoThumbnailPlugin
      ios:
        pluginClass: VideoThumbnailPlugin
      web:
        pluginClass: VideoThumbnailWeb
        fileName: video_thumbnail_web.dart